// English versions of the carried-over articles (same blocks as ARTICLES)
import type { Block } from './insights';
import { asset } from '../utils/asset';

export const ARTICLES_EN: Record<string, { title: string; body: [string, string]; blocks: Block[] }> = {
  'zachem-startapu-strategiya': { title: "Why a startup needs a strategy when everything keeps changing", body: ["“It’s too early to think about strategy — let’s test hypotheses” — that’s what almost every startup thinks.", "Launching a product is easy now: vibe-code an MVP in a couple of weeks, run ads, even get your first users."], blocks: [
    {"type": "p", "text": "“It’s too early to think about strategy — let’s test hypotheses” — that’s what almost every startup thinks."},
    {"type": "p", "text": "Launching a product is easy now: vibe-code an MVP in a couple of weeks, run ads and even get your first users. At this stage it can feel too early to think about strategy. Why pin anything down if everything keeps changing and will change again in a month?"},
    {"type": "p", "text": "But even while you test hypotheses and change the product, you are already choosing who a feature is for, what your ad creatives promise and what waits for later. Those decisions gradually add up to the product’s direction — even if you never put it into words."},
    {"type": "p", "text": "As a product grows, so does uncertainty. The less you understand who you are and who you’re for, the harder it is to make consistent decisions. A new feature appears for one audience, the landing page is rewritten for another, and the ads promise something else again. Every attempt costs time, money and energy. So what worked? What should you build on?"},
    {"type": "p", "text": "That’s why it helps to pin down at least the bare essentials — something to lean on when you decide."},
    {"type": "h3", "text": "You don’t need a 40-page strategy. Four questions are enough to start."},
    {"type": "h2", "text": "4 questions worth answering even at a product’s start"},
    {"type": "h3", "text": "1. Who comes, who pays, and at what moment"},
    {"type": "p", "text": "“Small businesses” or “everyone who needs content” is too broad. It’s good if you can picture a person in the specific situation in which they open your product."},
    {"type": "p", "text": "Say you’ve built an AI service that transcribes calls. Team leads, researchers, content makers and many others could use it. One technology, different jobs. You could, for instance, focus on the team lead who, after four calls in a row, no longer remembers who promised what."},
    {"type": "p", "text": "This helps you choose whom to invite to test new features and whose requests come first. Otherwise it’s easy to get lost in contradictory feedback. You can’t tell what to improve until you’ve decided for whom."},
    {"type": "h3", "text": "2. What people choose your product instead of"},
    {"type": "p", "text": "How does a person solve their problem without you? The answer shows what improvement would make them give up the old way and come to you."},
    {"type": "p", "text": "For the AI transcriber: does the person take notes by hand, use another service, re-listen to the recording, load the transcript into NotebookLM? Or do they do nothing at all because it doesn’t matter to them? If ordinary notes are good enough, you first have to explain why they should swap their habit for something new."},
    {"type": "p", "text": "Look for the answer in conversations with users and in what they actually do. A working rule: ask and observe, don’t assume. It’s an important reality check."},
    {"type": "h3", "text": "3. What result you promise"},
    {"type": "p", "text": "Put your promise into a single sentence. It will come in handy for landing pages and the product’s main flow. Is it clear what result the person will get? Can they really get it from the product?"},
    {"type": "p", "text": "For the AI transcriber you’re tempted to say: “We turn audio into text.” But that describes a function, not a promise. A team lead, for example, needs to see quickly who will do what by when. Then the promise could be: “A ready task list with owners and deadlines five minutes after the call.”"},
    {"type": "p", "text": "If the promise drifts, it’s easy to disappoint users. Say the creative promised time saved and everything like magic, and the service produced a transcript that has to be sorted out by hand. The person came to save time and got something else. A broken promise is a reason never to come back."},
    {"type": "h3", "text": "4. Why they’ll choose you"},
    {"type": "p", "text": "What do you have that a clone someone builds over a weekend won’t? What’s so good that a user would prefer your product? “Well, ours is more convenient” is not an answer."},
    {"type": "p", "text": "For the transcriber it could be this: the service knows the team and files the tasks into the tracker itself, rather than just handing over text."},
    {"type": "p", "text": "Without an answer to this question you can spend time, energy and money on things that don’t affect the choice at all — and hide what users really come for."},
    {"type": "p", "text": "Gather your answers on one page, marking what’s confirmed and what’s still a hypothesis. That gives you a shared foundation for the next landing page, feature and ad creative — and for the product and brand design too. Come back to the answers with new data: if the data contradicts them, it’s time to revisit."},
    {"type": "p", "text": "If you’d rather not work through these questions alone, at [Skip Design](https://skip.design) we help startups put together a strategy at the start: we run a session with the team, go through user interviews and pin down what the product and the brand can rely on."},
  ] },
  'kak-smysly-brenda-stanovyatsya-produktovymi-resheniyami': { title: "How brand meanings become product decisions", body: ["A company spent several months and a budget on a rebrand and made a beautiful deck with a mission, vision and values.", "Everyone admired it and handed it to marketing. And the product lives a life of its own."], blocks: [
    {"type": "p", "text": "A company spent several months and a budget on a rebrand. They made a beautiful deck with a mission, a vision and values. Everyone admired it and handed it over to marketing. And the product lives a life of its own."},
    {"type": "p", "text": "Time passes, the product team sits over the backlog and ideas come up: “What if we made an onboarding with a storyline?”, “Let’s build an AI agent — everyone’s doing AI!” Stop. What does that have to do with the brand the company worked on?"},
    {"type": "p", "text": "Branding isn’t pictures — it’s a system that affects everything at once: marketing, communication and the product. If nothing happens to the product after a rebrand, the gap between the brand people are meant to see and the one they actually experience will keep growing."},
    {"type": "h2", "text": "How not to get it wrong"},
    {"type": "h3", "text": "A common mistake"},
    {"type": "p", "text": "Grabbing one clear word from the brand platform and basing every decision on it alone."},
    {"type": "h3", "text": "The right way"},
    {"type": "p", "text": "Break all the meanings down and bring them down to earth."},
    {"type": "h3", "text": "How meanings connect to the product"},
    {"type": "p", "text": "When we build a brand platform, we use the Means-End Chain logic. Simplified, the chain looks like this:"},
    {"type": "p", "text": "product attribute → functional benefit → emotional benefit → value."},
    {"type": "p", "text": "It links what the product does to what a person feels. In product development you can run this logic backwards: if the brand promises people something, what has to appear or change in the product for that?"},
    {"type": "h2", "text": "6 steps to turn an abstract mission into a button"},
    {"type": "p", "text": "Let’s take Duolingo as an example."},
    {"type": "h3", "text": "1. Meaning"},
    {"type": "p", "text": "What the brand promises a person."},
    {"type": "p", "text": "Duolingo’s mission is to develop the best education in the world and make it universally available. In its strategy the company speaks separately about motivation: the product should make you want to come back to learning every day."},
    {"type": "p", "text": "Several meanings stand out: accessibility, quality of learning, the wish to keep going. Each of them leads to its own product decisions."},
    {"type": "p", "text": "Take accessibility. In our breakdown it’s both the chance to start and the chance to fit learning into your rhythm of life — with all the excuses like “I’ll definitely study tomorrow!”"},
    {"type": "quote", "text": "Pay special attention to the verbs: they show an action, and an action is, among other things, a button in the interface."},
    {"type": "h3", "text": "2. Principle"},
    {"type": "p", "text": "The translator between a meaning and a feature."},
    {"type": "p", "text": "For the accessibility promise the principle could be: the product should help a person study regularly, even when the enthusiasm is gone."},
    {"type": "p", "text": "Different solutions can grow out of it: short lessons, reminders, visible rewards for consistency."},
    {"type": "p", "text": "With the consistency principle, one thing matters: the mission itself doesn’t say “make a streak”. Between the mission and the feature there is a choice — which barrier we remove, and how."},
    {"type": "h3", "text": "3. Behaviour"},
    {"type": "p", "text": "What will the person do?"},
    {"type": "p", "text": "Now define a concrete action to see whether the principle will work."},
    {"type": "p", "text": "Here’s a person who does a few lessons today and comes back tomorrow. But just opening the app isn’t enough: the product wants to help people learn regularly."},
    {"type": "p", "text": "That’s how an abstract “keep up motivation” becomes behaviour you can observe."},
    {"type": "h3", "text": "4. Mechanic"},
    {"type": "p", "text": "What the product does to make the behaviour happen."},
    {"type": "p", "text": "Duolingo has a streak — a count of days studied in a row. To keep the streak you have to complete at least one lesson, and the number of days makes the progress visible."},
    {"type": "p", "text": "There’s a streak freeze for a few days, to keep the progress when you miss one. The company explains it by saying a little flexibility helps people keep going. It’s an important nuance: if learning is meant to fit into life, you have to allow for life getting in the way."},
    {"type": "h3", "text": "5. Place"},
    {"type": "p", "text": "Where and when the mechanic shows up in the interface."},
    {"type": "p", "text": "Even a good mechanic can be hidden in the interface so that it doesn’t work. Duolingo shows the streak extension after the first lesson of the day — a bright little flame, a delightful animation. The person has just made an effort and gets confirmation right away. And of course every lesson ends with the owl, who praises you and, after a flawless lesson, flies off almost into space."},
    {"type": "p", "text": "To choose where to confirm the streak, don’t ask “where do we put the flame?” but “at what moment will the flame make the person want to keep going?”"},
    {"type": "h3", "text": "6. Metrics"},
    {"type": "p", "text": "How to tell the solution works and supports the original meaning."},
    {"type": "p", "text": "The answer is metrics — product ones and brand ones. With Duolingo you can look at both."},
    {"type": "p", "text": "Product: DAU, retention, the average streak length. Brand: the association “Duolingo is about the habit”, not “Duolingo is about a language”. And it works: people admit they’re more afraid of letting the owl down than keen to learn Spanish. Though Spanish too, of course."},
    {"type": "p", "text": "In short, any meaning from the brand platform turns into a button the user actually presses. The meaning sets the direction, the principle helps choose the solution, and the metrics check whether the meaning has become a real experience of the product."},
    {"type": "p", "text": "If you need help translating brand meanings into the language of the product, write to us. We love this and we’re good at it."},
  ] },
  'raznica-mezhdu-product-vision-i-brand-vision': { title: "The difference between product vision and brand vision", body: ["They’re easy to confuse, because both talk about the future. But they answer different questions.", "Brand vision: where do we want to be as a brand in 2–5 years? Product vision: what must the product become to make that future possible?"], blocks: [
    {"type": "p", "text": "They’re easy to confuse, because both talk about the future. But they answer different questions."},
    {"type": "p", "text": "🤍 Brand vision: where do we want to be as a brand in 2–5 years? What change do we want to create in the world, in culture, in the industry or in people’s lives?"},
    {"type": "p", "text": "It’s a big ambition — point B in the future that the brand is moving towards."},
    {"type": "p", "text": "🤍 Product vision: what must the product become to make that future possible?"},
    {"type": "p", "text": "Product vision brings the brand’s ambitions down to the level of a specific interface, product or service — what to build, draw and code tomorrow. It translates point B into a concrete user experience and result."},
    {"type": "p", "text": "Take GetYourGuide as an example:"},
    {"type": "p", "text": "🤍 Brand vision. Revolutionize how people discover and enjoy travel experiences."},
    {"type": "p", "text": "🤍 Product vision. Create a global marketplace where a traveller planning or already on a trip can quickly find the right experience for their interests and circumstances, compare trustworthy options and book it with confidence."},
    {"type": "p", "text": "So:"},
    {"type": "p", "text": "Brand vision → what future we want to create."},
    {"type": "p", "text": "Product vision → what the product must become to make that future possible."},
    {"type": "h2", "text": "And what should change in a person’s life thanks to your product?"},
    {"type": "p", "text": "Product vision helps answer this question."},
    {"type": "p", "text": "Product vision is useful even to small teams: it helps you check against the goal, stay focused and set priorities."},
    {"type": "p", "text": "We have a working formula. It isn’t from textbooks or manuals, but in practice it helps set a clear goal:"},
    {"type": "p", "text": "Create [an environment / a way / a tool] so that [a specific person in a specific state] can [an observable result] within [a time horizon]."},
    {"type": "p", "text": "Let’s take it apart:"},
    {"type": "p", "text": "[an environment / a way / a tool] — what the product is. A platform, an app, a tool, a builder, a methodology."},
    {"type": "p", "text": "[a specific person in a specific state] — narrow the audience and account for context. Just “parents”, for example, is too broad. “Parents in the morning rush” is a clear scenario you can build a product for."},
    {"type": "p", "text": "[an observable result] — a measurable, visible criterion of success."},
    {"type": "p", "text": "[a time horizon] — set limits. For example: in 5 minutes, 15 minutes a day, in the first month, by 2028."},
    {"type": "h3", "text": "For example:"},
    {"type": "p", "text": "Create a mobile assistant app so that parents of 6–10-year-olds in the morning rush can get their child ready for school in 15 minutes."},
    {"type": "p", "text": "With a statement like this the team can ask itself at any moment:"},
    {"type": "h3", "text": "Does what we’re doing right now bring us closer to our vision?"},
  ] },
  'chto-dolzhno-izmenitsya-v-zhizni-cheloveka-blagodarya-produktu': { title: "What should change in a person’s life thanks to your product?", body: ["Product vision helps answer this question.", "Product vision is useful even to small teams: it helps you check against the goal, stay focused and set priorities."], blocks: [
    {"type": "p", "text": "Product vision helps answer this question."},
    {"type": "p", "text": "Product vision is useful even to small teams: it helps you check against the goal, stay focused and set priorities."},
    {"type": "p", "text": "We have a working formula. It isn’t from textbooks or manuals, but in practice it helps set a clear goal."},
    {"type": "p", "text": "Create [an environment / a way / a tool] so that [a specific person in a specific state] can [an observable result] within [a time horizon]."},
    {"type": "p", "text": "Let’s take it apart:"},
    {"type": "p", "text": "[an environment / a way / a tool] — what the product is. A platform, an app, a tool, a builder, a methodology."},
    {"type": "p", "text": "[a specific person in a specific state] — narrow the audience and account for context. Just “parents”, for example, is too broad. “Parents in the morning rush” is a clear scenario you can build a product for."},
    {"type": "p", "text": "[an observable result] — a measurable, visible criterion of success."},
    {"type": "p", "text": "[a time horizon] — set limits. For example: in 5 minutes, 15 minutes a day, in the first month, by 2028."},
    {"type": "p", "text": "For example,"},
    {"type": "p", "text": "Create a mobile assistant app so that parents of 6–10-year-olds in the morning rush can get their child ready for school in 15 minutes."},
    {"type": "p", "text": "With such a statement the team can ask itself at any moment: does what we’re doing right now bring us closer to our vision?"},
  ] },
  'konstruktor-missii-brenda': { title: "The mission builder", body: ["The builder rests on one idea: there are four different ways to arrive at the answer to “Why do we do this?”", "The search for a brand mission often turns into a race for the perfect phrase, like Nike’s or Apple’s."], blocks: [
    {"type": "p", "text": "The builder rests on one idea: there are four different ways to arrive at the answer to “Why do we do this?”"},
    { type: 'image', src: asset("/media/insights/konstruktor-missii-brenda/1.png"), shape: "auto", ratio: 1.7778 },
    {"type": "p", "text": "Written by the [Skip Design](https://skip.design/) team — we made the [brand mission builder](https://www.figma.com/community/file/1546797774916412046) described below."},
    {"type": "p", "text": "UPD (6 April 2026) — we shared the results [in part two.](https://vc.ru/id5092248/2854425-konstruktor-missii-kak-sformulirovat-tseli-dlya-biznesa)"},
    {"type": "p", "text": "The search for a brand mission often turns into a race for the perfect phrase, like Nike’s or Apple’s. Teams fall into a trap: they brainstorm, get creative, lock themselves in meeting rooms to find those inspiring words. And end up with a hollow statement cut off from reality: everyone reads it their own way, and sometimes it’s written once and forgotten."},
    {"type": "p", "text": "It happens because a business looks at the market leaders, looks for beautiful words first and then tries to fit meanings to them. Being inspired by other people’s statements is fine. But to find your own mission, remember:"},
    {"type": "h2", "text": "first the essence and the meaning, then the form"},
    {"type": "p", "text": "What comes first isn’t the words but what they mean — to the brand, the team and the customers. For a mission to come alive, it needs roots as well as a form. It doesn’t have to be invented; it has to be discovered and brought out from within."},
    {"type": "p", "text": "To make the search easier, we developed a framework that helps find a starting point close to the team and the business. The mission then stops being a line on a slide and becomes a practical tool the team can use to build ad campaigns and communication or to test product hypotheses."},
    { type: 'image', src: asset("/media/insights/konstruktor-missii-brenda/2.png"), shape: "auto", ratio: 1.7778 },
    {"type": "h2", "text": "How the mission builder works"},
    {"type": "p", "text": "Every company is driven by something different: for some it’s the founder’s wild energy, for others unshakable ethical principles, for others a unique method or approach. Having gone through dozens of branding projects, we identified four approaches to finding a mission. They are four entry points that give different angles but lead to one thing — a clear mission that works."},
    {"type": "p", "text": "The approaches follow the same logic and have three stages: unload, assemble and squeeze."},
    {"type": "ol", "items": ["Unload. First you answer three open questions. Their purpose is to unload all the “raw material” without filters or self-censorship: thoughts, emotions, facts, associations. At this stage don’t look for the right answer — get out everything that’s inside.", "Assemble. Here you use a special builder template to put the first meaningful statement together from scattered ideas. This stage helps make connections and turn a tag cloud into a story.", "Squeeze. At the final stage you turn the long draft into a compact, strong phrase: find the core, cut the excess and add energy."]},
    { type: 'image', src: asset("/media/insights/konstruktor-missii-brenda/3.png"), shape: "auto", ratio: 2.8738 },
    {"type": "p", "text": "A good framework leads not to one right answer but to several possible, workable ones. That’s why the builder has different paths inside. Choose the one that resonates most, or go through all of them to see different sides of the meaning."},
    {"type": "h2", "text": "Approach 1 — the original energy"},
    {"type": "p", "text": "This is about an inner impulse: an irritation, an injustice or an imbalance you want to change. Not necessarily on a global scale — it can be a pain you face every day and want to handle differently."},
    {"type": "p", "text": "Who it’s for. Projects born out of protest, out of “I can’t not do this”, out of pure drive or the founder’s personal story. Often startups, independent projects, creative studios. They can be D2C brands challenging the giants, or media projects built around a burning issue."},
    {"type": "p", "text": "Why this approach. Their fuel is emotion. Forcing such projects into the frame of values or results means putting the fire out."},
    {"type": "h2", "text": "Approach 2 — the most important value"},
    {"type": "p", "text": "This approach helps you feel for the company’s inner core, its moral nerve. What matters to you so much that you won’t betray it — not for profit, convenience or trends?"},
    {"type": "p", "text": "Who it’s for. Projects built on unshakable principles. For example consulting, legal and financial firms, education projects, companies with a strong corporate culture, premium brands in real estate, finance and travel — brands for which how they do things matters as much as what they do."},
    {"type": "p", "text": "Why this approach. Their essence isn’t in the product but in a code. The mission becomes a manifesto of beliefs built around a clear foundation."},
    {"type": "h2", "text": "Approach 3 — a unique method or approach"},
    {"type": "p", "text": "This approach is for those whose main strength is a unique way of doing things. A “secret sauce”, a technology, a process or a signature point of view that sets them apart in the market."},
    {"type": "p", "text": "Who it’s for. Those who have created a unique process, technology or approach. IT and SaaS companies, tech startups, design bureaus, craft workshops, research projects and R&D labs."},
    {"type": "p", "text": "Why this approach. Their difference isn’t in the goal but in how they reach it. The mission has to explain what’s unique about the method, because the method is their main contribution to the world."},
    {"type": "h2", "text": "Approach 4 — the trace or transformation after the interaction"},
    {"type": "p", "text": "This approach focuses on the result and the impact you bring to the world or to a customer’s life. What changes after someone deals with you? What does the world or the person become thanks to your product?"},
    {"type": "p", "text": "Who it’s for. Projects whose main goal is measurable impact on the world, the customer or the industry. For example venture funds and accelerators, well-being and productivity companies, B2B services and SaaS platforms that make business more efficient, HR and career-growth companies, medical clinics and others."},
    {"type": "p", "text": "Why this approach. They think in terms of “before and after”. Their mission is a promise of a concrete result, a change for the better."},
    { type: 'image', src: asset("/media/insights/konstruktor-missii-brenda/4.png"), shape: "auto", ratio: 1.7778 },
    {"type": "h2", "text": "Which approach to choose"},
    {"type": "p", "text": "One of the approaches usually resonates more than the others. If it’s hard to choose, open the [builder](https://www.figma.com/community/file/1546797774916412046) and answer the first question: it will point you in a direction."},
    {"type": "p", "text": "To show how the tool works, we did the most honest thing — we ran the builder itself through the builder. We applied all four approaches and looked at how different in focus, yet close in essence, the statements would be. Here’s what came out:"},
    {"type": "h3", "text": "Approach: the original energy"},
    {"type": "p", "text": "We bring lightness, beauty and meaning back to the search for a mission."},
    {"type": "p", "text": "Focus: this statement was born as a protest against stuffy, boring and pointless strategy sessions. It’s charged with the wish to change everything and answers the question: “What annoys us about the current approach to missions?”"},
    {"type": "h3", "text": "Approach: the most important value"},
    {"type": "p", "text": "We turn the search for a mission into a conscious, thoughtful process."},
    {"type": "p", "text": "Focus: here the attention shifts from emotions to values. We set ourselves against “come up with it in an hour” or copying competitors, and stress the quality and honesty of the process itself."},
    {"type": "h3", "text": "Approach: a unique method"},
    {"type": "p", "text": "We give a systematic tool for putting a mission into words through immersion and self-understanding."},
    {"type": "p", "text": "Focus: this is the most functional statement. It describes the product — what it is and how it works."},
    {"type": "h3", "text": "The trace and transformation after the interaction"},
    {"type": "p", "text": "We believe businesses will reach strategic clarity and vision through our mission builder."},
    {"type": "p", "text": "The focus is on the result for the user. What do they get in the end? The statement describes the move from point A — fog, doubt — to point B — clarity and a confident look into the future."},
    {"type": "p", "text": "All four versions of the mission are right. Each reveals the builder in its own way and adds its own side of the meaning. A particular approach helps you find the main focus for now, and the builder’s clear structure makes the process systematic and takes it all the way to a clear statement."},
    {"type": "p", "text": "Whichever path you choose, the goal is the same — to find a mission that isn’t just beautiful but true and working. If you’d rather not go through it all alone, write to hi@skip.design."},
    { type: 'image', src: asset("/media/insights/konstruktor-missii-brenda/5.png"), shape: "auto", ratio: 5.8905 },
    {"type": "p", "text": "This is the first version of the builder. It was made by:"},
    {"type": "ul", "items": ["Ksyusha Aniskovich — thought it up and built it,", "Senya Sinitsa — produced and directed,", "Asha Saakian — believed we’d pull it off."]},
    {"type": "p", "text": "We’ll keep improving the builder, and every run-through will help make it more useful and precise. If you’d like to share feedback, write to Asha [on Telegram](https://t.me/AshaSaakian)."},
  ] },
  'prompt-dlya-proverki-metafory': { title: "A prompt for testing a metaphor", body: ["Without a metaphor any concept falls apart. You get a set of techniques that don’t hold their shape.", "At Skip Design we use our own methodology. Each criterion is a question that scores a metaphor from 1 to 5."], blocks: [
    {"type": "p", "text": "Without a metaphor any concept falls apart. You get a set of techniques that don’t hold their shape. That’s why at Skip Design we pay special attention to metaphors."},
    {"type": "h3", "text": "What makes a metaphor strong at all?"},
    {"type": "p", "text": "A strong metaphor:"},
    {"type": "ul", "items": ["rests on the overall spirit and state of things, not on dry features;", "makes you not just understand but feel and act;", "is rooted in bodily experience;", "gives rise to a system of consequences, not a one-off comparison;", "creates a third image that wasn’t there before;", "can live and grow in communication for years."]},
    {"type": "h3", "text": "At Skip Design we use our own methodology"},
    {"type": "p", "text": "Each criterion is a question that scores a metaphor from 1 to 5."},
    {"type": "p", "text": "1. Tangibility. Is it a comparison with something real and physical that’s easy to picture in detail?"},
    {"type": "p", "text": "2. Development. Can the metaphor be carried further? Does it spark new thoughts, or is it an empty phrase?"},
    {"type": "p", "text": "3. Focus. Which feature of the subject does the metaphor put first? Does it confuse by trying to highlight everything at once?"},
    {"type": "p", "text": "4. Lived experience. Is the metaphor connected to a person’s physical, bodily or everyday experience of the world?"},
    {"type": "p", "text": "5. Novelty. Does the metaphor create a new, unusual image — or does it sound like a cliché?"},
    {"type": "p", "text": "6. State. Does the metaphor convey the mood, the vibe of the situation — or only compare similar details?"},
    {"type": "p", "text": "7. Call to action. Does the metaphor push towards specific actions and decisions?"},
    {"type": "p", "text": "8. Cultural code. Does the metaphor match the shared values and usual way of thinking of people in a particular culture?"},
    {"type": "p", "text": "9. Room to expand. Does the metaphor have reserves — details and layers that can be unfolded in communication later?"},
    {"type": "p", "text": "10. Changing reality. Does the metaphor change the view of the problem and the product so much that a previously invisible solution becomes obvious?"},
    {"type": "h3", "text": "We put them into a prompt you can use to test metaphors"},
    {"type": "code", "text": "You are an expert in cognitive linguistics and brand strategy. You specialise in assessing the quality of metaphors using the Lakoff–Johnson method (conceptual metaphor theory) and Ufimtsev’s (the metaphysics of metaphor: “golden” vs “wooden” metaphors). The user will give you a metaphor and possibly a context (brand, product, audience, communication channel). If no context is given, assess it in general terms.\n\n## Your task\nScore the metaphor on 10 criteria. Each criterion gets 1 to 5 points.\n\n## 10 criteria\n\n01. TANGIBILITY (the “Anchor” principle) How much more concrete and physically tangible is the source domain (what we compare WITH) than the target domain (WHAT we compare)? A metaphor should explain the abstract through the tangible. 5 = the source is an everyday physical object, the target an abstraction. 1 = both concepts are equally abstract.\n\n02. DEVELOPMENT (the “Grid” principle) Does the metaphor generate a system of consequences? How many logical continuations can be drawn? Does one link pull others along? 5 = generates 5+ consequences, each enriching understanding. 1 = a one-off comparison with nothing behind it.\n\n03. FOCUS (the “Spotlight” principle) Which side of the phenomenon does the metaphor highlight? Which does it hide? Does this focus suit the task? 5 = highlights exactly what’s needed; what’s hidden isn’t critical. 1 = hides key aspects or muddles the focus.\n\n04. LIVED EXPERIENCE (the bodily anchor) Is the metaphor rooted in physical or everyday experience? “Happy is up” works because we straighten up when we’re glad. 5 = a direct link to universal bodily experience. 1 = an arbitrary intellectual construct without roots.\n\n05. NOVELTY (the “Chemical reaction” principle) Does the metaphor give birth to a new, third image that can’t be reduced to the sum of its parts? 1 + 1 = 3? 5 = a vivid third image appears that wasn’t there. 1 = just a shared feature, nothing new.\n\n06. STATE (the “Spirit, not blueprint” principle) Does the metaphor catch the vibe, the spirit, the state — or tediously compare surface details? This is the test for “golden” vs “wooden”. 5 = captures the overall spirit, state, way of being. 1 = only surface similarity on a single feature.\n\n07. CALL TO ACTION (the “Guidance” principle) What specific actions does the metaphor push towards? Does it dictate a strategy? 5 = directly dictates a strategy of action relevant to the task. 1 = no consequences for behaviour.\n\n08. CULTURAL CODE Is the metaphor in harmony with the values of the target culture and audience? 5 = full harmony with the audience’s values. 1 = conflicts with basic values or is unclear.\n\n09. ROOM FOR CREATIVITY Can the metaphor be developed further using “unused” parts of the source domain? 5 = the source domain is rich and can be developed for years. 1 = the source is exhausted by a single comparison.\n\n10. CHANGING REALITY Can the metaphor change how the problem is perceived and reveal a solution that wasn’t visible before? 5 = reframes perception, opens new approaches. 1 = mere decoration of speech.\n\n## Answer format\n\n### Metaphor score [✦ Golden / ◆ Silver / ▪ Wooden] — [overall score]/5\n\n### Summary\n3–4 sentences: the main thing about the metaphor, its strength and weakness.\n\n### Score by criterion\nFor each criterion: [number]. [name] — [score]/5 [2–3 sentences: why this score]\n\n### How to strengthen it (only if the verdict isn’t “golden”)\n1–2 specific recommendations for reworking the metaphor.\n\n## Verdict rules\n- Average score ≥ 4.0 → ✦ Golden\n- Average score 2.5–3.9 → ◆ Silver\n- Average score < 2.5 → ▪ Wooden\n\n## Important\n- Be honest. Don’t inflate scores out of politeness.\n- If the metaphor is a cliché, say so plainly.\n- Write all explanations in English.\n- Don’t add criteria beyond the 10 listed.\n- If no context is given, assess it for a broad English-speaking audience."},
    {"type": "h3", "text": "How to use it:"},
    {"type": "p", "text": "1. Copy the prompt and give it to any AI model: Claude, Gemini, ChatGPT, DeepSeek."},
    {"type": "p", "text": "2. Give it the metaphor and the project context. For example, metaphor: time is an age of discovery. Context: beauty care for women 35+, launch of a new product line."},
    {"type": "p", "text": "3. The model breaks the metaphor down by criteria and gives a detailed analysis."},
  ] },
  'kak-ii-generiruet-metafory': { title: "How AI generates metaphors", body: ["5 AI models, 3 industries, 150 metaphors — finding out why there are architects, conductors and navigators everywhere.", "In this piece “metaphor” means more than a figure of speech on a landing page: it’s a frame that shapes how we see reality and make decisions."], blocks: [
    {"type": "p", "text": "5 AI models, 3 industries, 150 metaphors — finding out why there are architects, conductors and navigators everywhere."},
    {"type": "p", "text": "“We are architects of solutions”, “navigators in the world of finance”, “conductors of processes”, “translators from the language of business” — you’ve surely seen examples like these. A couple of years ago this may have worked: it helped stand out and build a strong image. Now it’s a cliché that gives away an AI."},
    {"type": "p", "text": "In this piece we say “metaphor”, but not as a figure of speech or a trick in landing-page copy — more broadly. A metaphor helps convey the essence quickly through a familiar image and sets a frame that shapes how we perceive reality and make decisions."},
    {"type": "p", "text": "And since AI models are everywhere, there are more clichés than ever. The first time, ChatGPT or DeepSeek surprise you: fresh, precise, wow. But in constant use you notice that different models use the same patterns for different industries."},
    {"type": "p", "text": "We checked — here are the results of the experiment and our observations."},
    {"type": "h3", "text": "The experiment"},
    {"type": "p", "text": "We wrote a prompt for generating metaphors by the rules Lakoff and Johnson left us: with a source domain, an unfolding, a logic of highlighting and hiding, and consequences."},
    {"type": "p", "text": "We ran the prompt through five models: ChatGPT, DeepSeek, Gemini 3.1 Pro Preview, Claude Opus 4.6 and Grok. Each was asked for 10 metaphors for three different industries: law firms, fintech and real estate."},
    {"type": "p", "text": "150 metaphors in total. We read them all and broke them down into patterns."},
    {"type": "h3", "text": "5 domains AI models draw metaphors from"},
    {"type": "p", "text": "Whatever industry you put into the prompt, the models draw metaphors from five domains: navigation, the body, craft, architecture and botany. That’s 43% of all the metaphors. The other 57% come from 20 other domains, one or two metaphors each."},
    { type: 'image', src: asset("/media/insights/kak-ii-generiruet-metafory/1.png"), shape: "auto", ratio: 2.0746 },
    {"type": "p", "text": "The safest pattern in AI metaphors is navigation. Every model produces it in all three industries. Architecture shows up in law and real estate. In those two industries it lands as foundations and walls, while in fintech architecture turns into hydraulics and flow. When personalisation or a flexible approach to the client is needed, the AI starts sewing, cutting and taking measurements."},
    {"type": "h3", "text": "Patterns shared by all the models"},
    {"type": "p", "text": "Strip out the industry names and all 150 metaphors merge into one portrait. AI models see business as a living but sick organism that needs a pilot-surgeon-translator: cut away the excess and direct a beautiful result. Romantic, if you don’t think about it."},
    {"type": "h3", "text": "1. The expert as a translator of reality — the meta-pattern"},
    {"type": "p", "text": "In all three fields the models divide the world into chaos/the invisible and order/the understandable, and place the company between them as a bridge. So a professional is above all someone who interprets and explains. An obvious function."},
    {"type": "p", "text": "Law: Translating from the language of the law into the language of business, deciphering a code."},
    {"type": "p", "text": "Fintech: Translating from banking protocol into human language, the role of an invisible synchroniser."},
    {"type": "p", "text": "Real estate: Translating the language of a client’s wishes into the language of the market, decoding hidden motives."},
    {"type": "h3", "text": "2. Metaphors as the physical suffering of the body"},
    {"type": "p", "text": "Here DeepSeek really piled on the cringe. It’s generally rather aggressive and the harshest in the metaphors it offers. But it isn’t the only one."},
    {"type": "p", "text": "Law: The internal bleeding of compliance, the scar tissue of precedent."},
    {"type": "p", "text": "Fintech: Clots in the arteries of payments, an arrhythmia of transactions."},
    {"type": "p", "text": "Real estate: A stalled construction project as a bad tooth, a down payment as a blood transfusion to yourself."},
    {"type": "p", "text": "So AI uses biological fear to stress how critical a situation is. Risk in these metaphors is always a threat to the organism’s life."},
    {"type": "h3", "text": "Complexity as dirt and noise to be removed"},
    {"type": "p", "text": "In every field the intellectual product is a pure concentrate obtained by removing excess chaos."},
    {"type": "p", "text": "Law: Separating slag from ore in arguments, cleaning the dust off facts."},
    {"type": "p", "text": "Fintech: Distilling big data, boiling raw information down to an essence."},
    {"type": "p", "text": "Real estate: X-raying a property, judging a deal’s freshness like checking a fish."},
    {"type": "h3", "text": "Business as art and spectacle"},
    {"type": "p", "text": "Working with a client is seen as a production in which the audience’s role and an emotional finale matter."},
    {"type": "p", "text": "Law: A trial as directing and editing, or a symphony orchestra."},
    {"type": "p", "text": "Fintech: The financial community as a choir, transactions as juggling."},
    {"type": "p", "text": "Real estate: A flat viewing as a casting or a short-film shoot, a property manager as the conductor of deaf musicians."},
    {"type": "h3", "text": "5. The more abstract the industry, the more bodily the metaphors — and vice versa"},
    {"type": "p", "text": "Metaphors always move from the concrete to the abstract. But AI models add the opposite vector too: from the abstract to the bodily and material. Fintech, for example, is the most abstract of the three industries: invisible transactions, digital processes, blockchain. And for fintech the models generate material, bodily metaphors: circulation, breathing, a muscular frame, fermentation, the immune system."},
    {"type": "p", "text": "28% of fintech metaphors describe invisible processes"},
    {"type": "p", "text": "Real estate is a physical industry. It has houses, walls, rooms. Yet it gets more emotional metaphors and metaphors of belonging: a second skin, a tribe, a dance, the carpet of life. The overly concrete gets some abstraction added."},
    {"type": "h3", "text": "6. No model generates 10 unrelated metaphors"},
    {"type": "p", "text": "Within a list of 10 metaphors there are 2–3 groups with related sources. That means metaphors aren’t generated by free association."},
    {"type": "p", "text": "Typical groups:"},
    {"type": "ul", "items": ["Organic: gardening + ecosystem + immune system + fermentation — about growth, balance, adaptation.", "Engineering: architecture + clockwork + hydraulics + navigation — about precision, control, structure.", "Craft: weaving + forging + pottery + tailoring — about mastery, handwork, uniqueness.", "Communication: translation + directing + conducting — about mediation, interpretation, coordination."]},
    {"type": "h3", "text": "How the metaphors differ by industry"},
    {"type": "p", "text": "When the industry changes, so does the metaphor’s focus. Unexpectedly, the models laid the industries out along a time axis. Lawyers live in the past: they dig and restore. Fintech lives in the present: it watches the pulse, the current and the sluices in real time. Real estate lives in tomorrow: it plants trees, puts down roots, builds bridges to the future."},
    {"type": "h3", "text": "Law — statics and repair"},
    {"type": "p", "text": "Most metaphors look to the past — archaeology and restoration — or to reinforcement — architecture and the skeleton. There’s a strong emphasis on surgical precision in stepping into conflicts."},
    {"type": "p", "text": "The main goal is to restore integrity or protect it."},
    {"type": "h3", "text": "Fintech — flow and energy"},
    {"type": "p", "text": "Right, money flows."},
    {"type": "p", "text": "The metaphors shift towards dynamics. There are few buildings, but the hydraulics of payments, the power grid of liquidity and the distillation of data appear."},
    {"type": "p", "text": "Fintech has metaphors of hidden connections: mycelium, for example, for decentralised finance."},
    {"type": "p", "text": "The main goal is to ensure speed and continuity of movement."},
    {"type": "h3", "text": "Real estate — emotion and identity"},
    {"type": "p", "text": "Hard to argue here: when we’re being sold a home, it’s always about emotion. The dream life and a wonderful future in a new development."},
    {"type": "p", "text": "A layer of relationship metaphors appears, along with a pattern of the perfect match (chemistry, love). Looking for a home is compared to matchmaking or a casting, and the home itself to a shell or a second skin."},
    {"type": "h3", "text": "How the models’ metaphors differ"},
    {"type": "p", "text": "Each model has its own way of thinking."},
    { type: 'image', src: asset("/media/insights/kak-ii-generiruet-metafory/2.png"), shape: "auto", ratio: 0.8515 },
    {"type": "h3", "text": "Leaderboard of AI models by metaphor uniqueness"},
    {"type": "p", "text": "DeepSeek is the most creative of all the models. It generates four times as many unique metaphors as ChatGPT."},
    { type: 'image', src: asset("/media/insights/kak-ii-generiruet-metafory/3.png"), shape: "auto", ratio: 2.6679 },
    {"type": "p", "text": "DeepSeek is sometimes so shocking that while analysing all the metaphors we invented a cringe-meter, measured in deepseeks. See for yourself:"},
    {"type": "ul", "items": ["Managing a building is conducting an orchestra of deaf musicians. Every resident is sure they’re playing a solo and hears only themselves, and the property manager’s job is simply to keep them from talking over each other.", "Capital growth is fermentation. Money has to “ferment” in a dark place undisturbed, and the investor mustn’t “lift the lid” too early or they’ll ruin the process.", "Assessing liquidity is checking a fish for freshness. The expert inspects the deal for “slime” and “grey gills”, knowing no discount can save a rotten property.", "A down payment is a blood transfusion to yourself. A person takes a resource from one arm to pour it into the other, while the bank plays the nurse checking the deal’s “haemoglobin”.", "A blockchain transaction is footprints in the snow."]},
    {"type": "h3", "text": "So what now?"},
    {"type": "p", "text": "Use AI models as a tool, but keep in mind that they drag clichés along with them."},
    {"type": "p", "text": "Meaning is a responsibility that can’t be delegated to an algorithm."},
  ] },
  'yuridicheskie-dokumenty-dlya-sajtov-i-prilozhenij': { title: "A cheat sheet on legal documents", body: ["We made a practical cheat sheet for product teams, designers and founders.", "When a website, app or bot launches, the legal side is often the last thing anyone remembers — after the release."], blocks: [
    {"type": "p", "text": "Together with the Poponina.legal team, we at Skip Design made a cheat sheet on legal documents in digital products."},
    { type: 'image', src: asset("/media/insights/yuridicheskie-dokumenty-dlya-sajtov-i-prilozhenij/1.png"), shape: "auto", ratio: 1.7778 },
    {"type": "p", "text": "When a website, app or bot launches, the legal side is often the last thing anyone remembers — after the release. As a result the documents are either missing or placed as a formality and don’t cover the real risks."},
    {"type": "p", "text": "We decided to put together a basic guide: where exactly legal requirements arise in a digital product and which documents are usually needed."},
    {"type": "p", "text": "The result is a practical cheat sheet for product teams, designers and founders."},
    {"type": "h3", "text": "Inside:"},
    {"type": "p", "text": "• where the law meets interfaces and user flows"},
    {"type": "p", "text": "• which documents a website, app or bot needs • where and how to place them properly"},
    {"type": "p", "text": "• common mistakes and good practices"},
    {"type": "h3", "text": "The document has three parts:"},
    {"type": "p", "text": "① Legal risks in digital products We look at the stages of a product where legal requirements appear."},
    {"type": "p", "text": "② Documents for a website, bot or app We listed the main documents and showed where they usually belong in the interface."},
    {"type": "p", "text": "③ Examples and recommendations We go through real situations and share practical advice."},
    {"type": "p", "text": "You can view the document [here](http://disk.yandex.ru/i/z7WB1YUJSdWyHw) — no sign-ups or registration."},
    {"type": "p", "text": "If the cheat sheet was useful, leave comments and questions — we’ll be happy to discuss."},
  ] },
  'pochemu-ne-vse-brendy-mogut-ispolzovat-ii': { title: "Why not every brand can use AI", body: ["Using the classic “fast — good — cheap” triangle, we explain why some brands can use AI and others can’t.", "Mapped onto branding, the model shows what a brand puts first and what exactly it promises its customers."], blocks: [
    {"type": "p", "text": "Using the classic triangle of “fast — good — cheap”, we explain why some brands can use AI and others can’t."},
    {"type": "h2", "text": "The project triangle in the context of branding"},
    {"type": "p", "text": "The project management triangle is an old model. Of three parameters you have to pick two, because all three at once is utopia. However hard you try, one of them will sag."},
    {"type": "p", "text": "Mapped onto branding terms, the model helps you see what a brand puts first and what exactly it promises its customers."},
    {"type": "h2", "text": "Examples"},
    {"type": "p", "text": "Every brand holds a position in this model. Apple chooses “good + fast”, so its budgets for production, art direction and strategy are enormous. Apple, for instance, released a behind-the-scenes of its Apple Neo ad to show how many man-hours went into it. Linux offers “good + cheap” but takes time and expertise to get into. Canva offers “fast + cheap”, but without depth or uniqueness."},
    {"type": "p", "text": "Knowingly or not, a brand picks its zone. Invest in production or not, hire a team or AI operators, buy a stock picture or organise a shoot. It has a cost in two senses: in money and in value."},
    {"type": "h2", "text": "AI design seems high-quality"},
    {"type": "p", "text": "When the boom of Midjourney, Stable Diffusion and DALL-E began in 2022, it seemed utopia was possible in visual content production. Here they were — tools that let any business make anything visual fast, well and for pennies."},
    {"type": "p", "text": "The arguments for AI in design sound convincing: scaling content, hyper-personalisation, localisation, less load on routine tasks. For performance marketing, e-commerce and a stack of banners a day it really works."},
    {"type": "p", "text": "Klarna saved $10 million a year. Revolut generates marketing assets in-house in days instead of weeks. Hugo Boss has used AI in product cards since 2023, and nobody complains, because a product card has a practical job and isn’t meant to stir emotion."},
    {"type": "p", "text": "But people quickly learned to recognise AI content. So instead of utopia a new zone appeared — “seems high-quality”."},
    {"type": "p", "text": "“Seems high-quality” is when the visual quality is formally fine, but a gut feeling kicks in — something’s off. The picture looks expensive, yet you don’t feel any value. The content looks professional, yet reads as lazy and made without much effort. Pixel-perfect, while trust in the brand falls."},
    {"type": "p", "text": "To understand why, you need two notions: visual quality and perceived quality."},
    {"type": "h2", "text": "Visual quality ≠ perceived quality"},
    {"type": "p", "text": "Visual quality is a technical property of an image: resolution, detail, colour rendering, composition, no artefacts. Everything you can judge by looking at the picture as an object. On this parameter AI generation is on a par with professional photography, and it keeps improving."},
    {"type": "p", "text": "Perceived quality is how the audience judges content in the context of the brand. What matters here isn’t only whether it looks good. It’s how much effort went into it, whether a person made it, whether it’s unique, whether the brand respects the audience’s ability to tell generated content apart."},
    {"type": "quote", "text": "Perceived quality is a judgement of the effort put in, not of the result."},
    {"type": "p", "text": "Before AI went mainstream, all visuals were assumed to be authentic. Photographers, models, stylists, designers, art directors — each specialist brought their own view into the shared result. Authenticity didn’t need proving."},
    {"type": "p", "text": "Now visual quality can be had with almost no human effort, and so authenticity is no longer free. It’s a scarce resource. For brands whose promise rests on craft, handwork and humanity, losing authenticity means losing the product."},
    {"type": "p", "text": "The German philosopher Walter Benjamin described a similar phenomenon in 1936 (no AI whatsoever) in his essay “The Work of Art in the Age of Mechanical Reproduction”. The “aura” is the unique presence of a work, inseparable from its history and the context of its making. Mechanical reproduction destroys the aura. For AI content, researchers today use the term semi-aura — a partial aura, enough for the functional and rational but not for the emotional."},
    {"type": "p", "text": "That’s why brands that choose “fast + cheap” can use AI without reputational loss: their audience isn’t looking for an aura. A brand from the “good” zone, however, risks destroying exactly what it’s valued for."},
    {"type": "h2", "text": "Companies that failed with AI"},
    {"type": "p", "text": "Brands’ failures with AI generation fall into two fields: stepping onto emotional territory and breaking the brand’s promises. Sometimes both at once."},
    {"type": "h3", "text": "AI on emotional territory"},
    {"type": "p", "text": "Coca-Cola, “Holidays Are Coming”, November 2024"},
    {"type": "p", "text": "Christmas is sacred territory for Coca-Cola. For decades the brand built an emotional bond around the holiday: the trucks, the snow, nostalgia and a recognisable jingle. Then three AI studios, generative models and a photorealistic remake of the legendary trucks ad. Visually, broadly fine — but the audience’s reaction: a soulless, dystopian nightmare. The company didn’t back down and tried again in 2025. The result: a negative reaction two years running."},
    {"type": "note", "text": "Source: [adsoftheworld.com](https://www.adsoftheworld.com/campaigns/holidays-are-coming-ai-generated) (2024)"},
    {"type": "note", "text": "Source: [adsoftheworld.com](https://www.adsoftheworld.com/campaigns/holidays-are-coming-ai-generated-2025-christmas-ad) (2025)"},
    {"type": "h3", "text": "Spotify Wrapped 2024, December 2024"},
    {"type": "p", "text": "Spotify’s Wrapped is a cultural event because it’s human-centred. Every year a new design system, an unexpected aesthetic, a sense that “they made an effort for me”. For the tenth-anniversary Wrapped, Spotify made an AI podcast with Google NotebookLM: synthetic voices discussed the year’s results, plus tags like Pink Pilates Princess. Positive mentions of the brand fell from 50.5% to 41.5%, and negative ones rose from 8.3% to 13.6%."},
    {"type": "p", "text": "In 2025 Spotify returned to a pre-internet aesthetic: mixtapes, CDs, scrapbooks, graffiti type, retro football graphics."},
    {"type": "h3", "text": "AI breaks the brand’s promises"},
    {"type": "p", "text": "Netflix × Arcane, November 2024"},
    {"type": "p", "text": "An AI-generated poster for the second season — fans spotted the deformed fingers. Alex Shahmiri of Riot Games wrote on X: “We intentionally don’t use AI for anything Arcane-related, because it’s disrespectful to the incredible artists who made the show.” The poster was pulled, and in 2025 Netflix released a five-point AI framework for partners — essentially a manifesto of where AI may and may not be used."},
    {"type": "note", "text": "Source: [techradar.com](https://www.techradar.com/computing/artificial-intelligence/netflix-removes-ai-art-poster-for-arcane-after-an-outcry-from-creators)"},
    {"type": "p", "text": "Gucci PRIMAVERA, February 2026"},
    {"type": "p", "text": "AI portraits of “Milanese grandmothers of 1976” for the Milan Fashion Week show and the debut of the new creative director, Demna. Despite the “created with AI” label, the brand got a wave of criticism: “What sad times, when Gucci can’t find a real Milanese grandmother to wear an outfit from 1976.”"},
    {"type": "p", "text": "The label didn’t help: people still see AI work as less valuable. Even when they can’t tell the two apart visually."},
    {"type": "p", "text": "You can look at the Gucci case from different angles: it’s quite possible that even the 22% drop in sales over the AI grannies was a strategic move."},
    {"type": "h2", "text": "Companies that turned AI down"},
    {"type": "p", "text": "When brands refuse to use AI, can you say they stop being tech-savvy or choose to lag behind? No. What emerges is extra value in being human."},
    {"type": "p", "text": "Dove — #KeepBeautyReal. A lifelong promise not to use AI to depict women. For Dove, authenticity is the core of the brand platform. AI visuals would break the promise of real beauty the brand has built on since 2004."},
    {"type": "p", "text": "Aerie — You can’t prompt this. No-AI became a marketing message and brought +23% sales in Q4 2025. The brand turned the absence of AI into a product feature."},
    {"type": "p", "text": "Procreate. A public refusal of generative AI in the product. For a tool whose audience is artists, it’s the only possible stance."},
    {"type": "p", "text": "Apple TV+, the series Pluribus. Vince Gilligan, creator of Breaking Bad, put the line “This show was made by humans” in the credits of his new series Pluribus. In an interview Gilligan called AI the world’s most expensive and energy-hungry plagiarism machine, and compared AI content to a cow chewing its cud."},
    {"type": "p", "text": "Heineken — #SocialOffSocials. The brand built a platform around the idea that real contact matters more than digital. A series of campaigns openly mocking AI. OOH posters in New York and the slogan: “Social networking — since 1873”."},
    {"type": "p", "text": "Each brand defends its position differently. In Heineken’s case the brand defends real human contact."},
    {"type": "p", "text": "Turning AI down is the same move that sets a brand apart. But the point of difference grows not from an attitude to technology but from the brand’s core."},
    {"type": "h2", "text": "How brands should use AI"},
    {"type": "p", "text": "The triangle makes it fairly easy to find your position. It’s a simplification, of course, that leaves out complex questions. But even at a high level the triangle helps define your AI strategy in design."},
    {"type": "h3", "text": "The “fast + cheap” zone: AI is your tool"},
    {"type": "p", "text": "Fintech, marketplaces, performance marketing, functional SaaS products. The audience in these segments engages with content for about 1.5 seconds. It isn’t looking for aura or authenticity; what matters is the information, the price and which button to press. AI banners, generative stock, automated localisation of visuals — all of it works and cuts production costs without reputational risk."},
    {"type": "p", "text": "Where to use it: banners for ad campaigns, product cards on marketplaces, A/B tests of visuals, background images for landing pages, icons and UI elements."},
    {"type": "p", "text": "What to avoid: even functional brands shouldn’t use AI in communication that works on image and emotion and shapes how the brand is seen."},
    {"type": "h3", "text": "The “good” zone: AI in visuals = self-destruction"},
    {"type": "p", "text": "Luxury, premium apps, craft brands, brands with a strong authorial stance. The audience pays for effort, emotion and uniqueness. It reads the symbolic love in handwork — and its absence in generation. Using AI in the visible layer of design undermines the promise the brand is built on."},
    {"type": "p", "text": "What to do: turn authenticity into a competitive advantage. Real people, real artists, the behind-the-scenes of the process. The label “made by humans” isn’t a limitation — it’s value."},
    {"type": "p", "text": "Can you use AI? Yes, but as infrastructure and in the invisible layer. Retouching, colour correction, rough sketches for internal discussion, resizing for formats. Anything that doesn’t go out as the final product."},
    {"type": "h3", "text": "The zone for brands somewhere in between"},
    {"type": "p", "text": "This is the hardest territory and also the biggest. Not luxury, but not mass market either. The audience is sensitive to quality but not ready to pay a premium. Both scalability and brand equity matter."},
    {"type": "p", "text": "A hybrid model works here: AI in operations, people in emotional communication."},
    {"type": "h3", "text": "AI in infrastructure — yes:"},
    {"type": "ul", "items": ["Localising visuals for different markets (with manual finishing)", "A/B testing banners and ad creatives", "Generating variations for targeted ads", "Preparing rough layouts and moodboards", "Automatic resizing and adapting to formats", "Internal presentations and prototypes"]},
    {"type": "h3", "text": "AI as a signature in the creative — no:"},
    {"type": "ul", "items": ["Ad campaigns and brand films", "Content associated with the brand’s values", "Visuals featuring people (especially faces, emotions, gestures)", "Anniversary, holiday and culturally significant campaigns", "Any content where the audience expects effort and emotion"]},
    {"type": "p", "text": "L’Oréal is a good example of the hybrid. Its in-house AI lab CREAITECH works for 37 of the group’s brands, but the company has publicly banned realistic AI-generated images of faces, bodies, hair and skin in external communication."},
    {"type": "p", "text": "The first rule of AI: don’t tell anyone about AI. AI shouldn’t be visible. As soon as the audience recognises AI generation, the devaluation mechanism kicks in — no matter how good the result looks."},
    {"type": "h2", "text": "The bottom line"},
    {"type": "p", "text": "AI made “fast + cheap” available to any business. But it didn’t make free what has always been expensive: the feeling that behind the content there’s a living person who cares."},
    {"type": "p", "text": "For functional brands that’s not a problem. For brands where emotion and quality matter, it’s a big risk. For everyone else it’s a question worth answering honestly: what exactly is the customer paying for? If for convenience and price, AI will speed up growth. If for craft and authenticity, AI may destroy what makes the brand valuable."},
    {"type": "p", "text": "Authenticity has become what quality used to be — a way to stand out in a world where the speed and volume of content grow endlessly. The only question is which side of the triangle your brand is on."},
  ] },
  'chto-delaet-metaforu-silnoj': { title: "What makes a metaphor strong?", body: ["Without a metaphor any concept falls apart. That’s why we pay them special attention.", "A strong metaphor rests on the spirit of things, makes you feel and act, and is rooted in bodily experience."], blocks: [
    {"type": "p", "text": "Without a metaphor any concept falls apart. That’s why we pay them special attention."},
    {"type": "p", "text": "In our view, a strong metaphor:"},
    {"type": "ul", "items": ["rests on the overall spirit and state of things, not on dry features;", "makes you not just understand but feel and act;", "is rooted in bodily experience;", "gives rise to a system of consequences, not a one-off comparison;", "creates a third image that wasn’t there before;", "can live and grow in communication for years."]},
  ] },
  'konstruktor-missii-kak-sformulirovat-celi-dlya-biznesa': { title: "The mission builder: how to put a business’s goals into words", body: ["We tested the mission builder on two large companies, a psychotherapist and a music duo.", "Any approach can lead to the same meanings, just in different wrapping. Here’s what we noticed."], blocks: [
    {"type": "p", "text": "Last autumn we developed the [mission builder](https://www.figma.com/community/file/1546797774916412046) — a framework that makes finding a mission easier and helps put it into words as a practical tool rather than just a pretty line on a slide."},
    { type: 'image', src: asset("/media/insights/konstruktor-missii-kak-sformulirovat-celi-dlya-biznesa/1.png"), shape: "auto", ratio: 1.7778 },
    {"type": "p", "text": "We tested the builder on two large companies, a psychotherapist and a music duo."},
    {"type": "h2", "text": "Here’s what we noticed:"},
    {"type": "p", "text": "1. Any approach can lead to the same meanings, just in different wrapping."},
    {"type": "p", "text": "Here, for example, is what the psychotherapist Adel came up with:"},
    {"type": "quote", "text": "I help people find relief and regain clarity. — the statement she arrived at on her own through the trace-and-transformation approach"},
    {"type": "quote", "text": "To help people form a new experience of relating to themselves, which opens the way to acting differently. — the statement that came out of the unique-method approach"},
    {"type": "p", "text": "2. The industry often dictates the approach. But if an approach seems obvious, take another. You’ll be surprised."},
    {"type": "quote", "text": "For a fintech company, say, the obvious path is the unique method. Psychotherapists will most likely choose trace and transformation. So will musicians. — Ksyusha, brand strategist at Skip Design"},
    {"type": "p", "text": "But sometimes a team argues for half an hour about which approach fits. So it’s better to give homework before the meeting, so that everyone thinks it over and gets in sync quickly."},
    {"type": "p", "text": "3. The builder is about the mission, though along the way it touches on values, approach and relationships with customers. The extra value of the result: the team gets in sync on meaning."},
    {"type": "p", "text": "4. Along the way, the team’s misalignment becomes visible. So as a team-building exercise for a small group, initiated by HR, it’s just the thing. You can even hold a tournament and see whose statement reaches the semi-final, the final and wins 😁"},
    {"type": "p", "text": "5. It’s quite possible the statement will gather dust somewhere in FigJam, but the process brings clarity and a sense of where to go."},
    {"type": "p", "text": "6. Five or six people per session is the maximum. The more precise the group, the faster the result."},
    {"type": "p", "text": "7. Once you have the final mission statement, multiply it by 10 and see what happens. It helps check that the mission isn’t aimed at a single touchpoint with the customer."},
    {"type": "p", "text": "8. The drawback of the current version: going through it with a guide is easier than on your own."},
    {"type": "p", "text": "If you’d rather not walk this path alone, write to hi@skip.design or to [Asha](http://t.me/ashasaakian) on Telegram."},
  ] },
};
